#Test the base URL
GET http://localhost:8080

### Create a user
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "firstName": "Ceo",
  "lastName": "owner",
  "email": "ceo@gmail.com",
  "password": "ceo123",
  "role": "both"
}

### Create a todo
POST http://localhost:8080/todo
Content-Type: application/json
#remember that the userID must match an existing one int rhe pgAdmin table and the column names must also match those in your schema

{
    "userId": 17,
    "todoName": "Delete a todo",
    "dueDate": "2026-09-04",
    "descrption": "sample delete todo",
    "isCompleted": false
}

### Get all Todos
POST http://localhost:8080/todos


### Get a todo by Id
GET  http://localhost:8080/todo/23


### update a todo by id
PUT  http://localhost:8080/todo/26
Content-Type: application/json

{
  "todoName": "Go shopping",
  "userId": 1,
  "dueDate": "2026-03-10",
  "description": "Buy or windowshop for a new mechanical keyboard",
  "isCompleted": false
}

### delete a todo by its id
DELETE http://localhost:8080/todo/34


### login a user
POST http://localhost:8080/auth/login
Content-Type: application/json

{
   "email": "pius@gmail.com",
  "password": "piusmwiti@123"
}


### get all users
POST http://localhost:8080/auth/users


### get todos to a specific user
GET  http://localhost:8080/todos/user/67